"""Upgraded ColorPlayer4

Revision ID: 095c7f837451
Revises: 0980c8d04f06
Create Date: 2025-08-08 15:17:00.676007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095c7f837451'
down_revision = '0980c8d04f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
