"""Upgraded ColorPlayer3

Revision ID: 0980c8d04f06
Revises: 32c034345549
Create Date: 2025-08-08 14:59:16.733677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0980c8d04f06'
down_revision = '32c034345549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('black_id', sa.String(), nullable=False))
        batch_op.create_foreign_key('black_name', 'colorPlayer', ['black_id'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('black_name', type_='foreignkey')
        batch_op.drop_column('black_id')

    # ### end Alembic commands ###
