"""Fix constraint naming2

Revision ID: 0a78447d03c0
Revises: da4092c1df2d
Create Date: 2025-08-08 13:49:53.971702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a78447d03c0'
down_revision = 'da4092c1df2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_archives')
    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('period',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('game_archive', type_='foreignkey')
        batch_op.create_foreign_key('game_archive', 'archives', ['archive_id'], ['id'])
        batch_op.drop_column('archive_player')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive_player', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('game_archive', type_='foreignkey')
        batch_op.create_foreign_key(None, 'archives', ['archive_player'], ['username'])
        batch_op.drop_column('archive_id')

    with op.batch_alter_table('archives', schema=None) as batch_op:
        batch_op.alter_column('period',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('id')

    op.create_table('_alembic_tmp_archives',
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('period', sa.DATE(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['profiles.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###
