"""empty message

Revision ID: 0cdf816e2b93
Revises: dbefedbf6b72
Create Date: 2025-08-08 14:52:24.571558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cdf816e2b93'
down_revision = 'dbefedbf6b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colorPlayer',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['profiles.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.drop_table('color_player')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('white_id', sa.String(), nullable=False))
        batch_op.create_foreign_key('white_name', 'colorPlayer', ['white_id'], ['username'])
        batch_op.drop_column('white')
        batch_op.drop_column('black')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('black', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('white', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('white_name', type_='foreignkey')
        batch_op.drop_column('white_id')

    op.create_table('color_player',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['profiles.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.drop_table('colorPlayer')
    # ### end Alembic commands ###
