"""Upgraded ColorPlayer2

Revision ID: 32c034345549
Revises: 0cdf816e2b93
Create Date: 2025-08-08 14:57:47.513679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c034345549'
down_revision = '0cdf816e2b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accu_white', sa.Float(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('accu_black')
        batch_op.drop_column('accu_white')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accu_white', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('accu_black', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.drop_column('accu_white')

    # ### end Alembic commands ###
