"""ColorPlayer primary keygame

Revision ID: 4834ebc38c27
Revises: ab17ed76afe4
Create Date: 2025-08-08 15:38:59.823742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4834ebc38c27'
down_revision = 'ab17ed76afe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.alter_column('game',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('game',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
