"""new one

Revision ID: 9e22742a6953
Revises: 4834ebc38c27
Create Date: 2025-08-08 15:45:59.242125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e22742a6953'
down_revision = '4834ebc38c27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
