"""Upgraded ColorPlayer5

Revision ID: ab17ed76afe4
Revises: 095c7f837451
Create Date: 2025-08-08 15:27:06.090479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab17ed76afe4'
down_revision = '095c7f837451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game', sa.String(), nullable=True))
        batch_op.create_foreign_key('game', 'games', ['game'], ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colorPlayer', schema=None) as batch_op:
        batch_op.drop_constraint('game', type_='foreignkey')
        batch_op.drop_column('game')

    # ### end Alembic commands ###
