"""Initial

Revision ID: dbefedbf6b72
Revises: 
Create Date: 2025-08-08 14:04:01.079723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbefedbf6b72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('pfp_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('joined', sa.DateTime(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_url'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('username')
    )
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('period', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['profiles.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('color_player',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['profiles.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('games',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('time_control', sa.String(), nullable=True),
    sa.Column('rules', sa.String(), nullable=True),
    sa.Column('fen', sa.String(), nullable=True),
    sa.Column('pgn', sa.String(), nullable=True),
    sa.Column('accu_white', sa.Float(), nullable=True),
    sa.Column('accu_black', sa.Float(), nullable=True),
    sa.Column('eco', sa.String(), nullable=True),
    sa.Column('white', sa.String(), nullable=True),
    sa.Column('black', sa.String(), nullable=True),
    sa.Column('tournament_url', sa.String(), nullable=True),
    sa.Column('match_url', sa.String(), nullable=True),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], name='game_archive'),
    sa.PrimaryKeyConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('color_player')
    op.drop_table('archives')
    op.drop_table('profiles')
    # ### end Alembic commands ###
