"""Fix ColorPlayer

Revision ID: e070f58686ea
Revises: 9e22742a6953
Create Date: 2025-08-08 16:58:07.781338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e070f58686ea'
down_revision = '9e22742a6953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('black_name'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('white_name'), type_='foreignkey')
        batch_op.create_foreign_key('white_name', 'colorPlayer', ['white_id'], ['id'])
        batch_op.create_foreign_key('black_name', 'colorPlayer', ['black_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('black_name', type_='foreignkey')
        batch_op.drop_constraint('white_name', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('white_name'), 'colorPlayer', ['white_id'], ['username'])
        batch_op.create_foreign_key(batch_op.f('black_name'), 'colorPlayer', ['black_id'], ['username'])

    # ### end Alembic commands ###
